/**
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTestFail {
    @Test public void testAppHasAGreetingFailure() {
        App classUnderTest = new App();
        assertNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
